---
title: "machine_replacement"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Small MDPs

# Libraries
```{r}
library(rcraam)
library(dplyr)
library(readr)
library(gtools)
library(reshape2)
library(MCMCpack)
loadNamespace("tidyr")
loadNamespace("reshape2")
loadNamespace("stringr")
```


# MDP - 1  (2 state 2 actions)

```{r}
create_small_mdp <- function(num.states = 2, 
                             num.actions = 3, 
                             discount = 0.8,
                             reward.range = c(-10 , 10), 
                             mdp_csv_filename = "simple_mdp_1.csv"
                             ){
  
  # drichlet dist for transition probabilities
  alpha <- rep(1, num.states)
  probabilities = rdirichlet(num.states*num.actions, alpha)   
  
    
  
  # rewards
  reward.list <- runif(num.states*num.actions , reward.range[1],reward.range[2])
  rewards <- matrix( reward.list, nrow=num.states, ncol=num.actions)
  
  
  
  
  # MDP table each row contains: 
  # c("idstatefrom","idaction","idstateto","probability","reward")
  mdp.df <-  data.frame(matrix(ncol = 5, nrow = 0))
  
  
  for(s in 1:num.states){
    for(a in 1:num.actions){
      # craam mdp is 0-based, unlike R arrays
      id.statefrom = s-1
      id.action = a-1
      
      
      id.reward = rewards[s,a]
      # Add transition to next states and record corresponding weights
      for(s.next in 1:num.states){
        id.stateto = s.next-1
        id.prob = probabilities[(s-1)*num.actions + a, s.next]
        
        new.row <- c(id.statefrom,id.action,id.stateto,id.prob,id.reward)
        mdp.df <- rbind(mdp.df, new.row)
        
      }
    }
  }
  
  colnames(mdp.df) <- c("idstatefrom","idaction","idstateto","probability","reward")
  write.csv(mdp.df, mdp_csv_filename, row.names = FALSE)
  return(mdp.df)
}

create_small_mdp()
```
