---
title: "Sngle Bellman Update - weighted ambiguity sets"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
source('utils.R')
source('experiment_helpers.R')
library(gtools)
library(dplyr)
library(rcraam)
library(ggplot2)
require(latex2exp)
#library(tidyr)
library(gridExtra)
library(gtable)
library(grid)
library(data.table)
```



```{r}
z <- c(1,2,3)
f <- c(0.2,0.3,0.5)
w <- c(1,1,1)
rcraam::worstcase_l1_w(z, f,w,  0.2)
rcraam::worstcase_l1_w_gurobi(z, f,w,  0.2)
rcraam::worstcase_linf_w_gurobi(z, f,w,  0.2)

```


# L1 Hoeffding


```{r}
set.seed(1658)
dir.name = "./results/"
file.name = "single_Bellman_update"
file.ext = ".csv"
file.results <- paste(dir.name, file.name, file.ext, sep = "")

method_names = list("L1.Hf",
                    "w.L1.Hf.anlyt",
                    "w.L1.Hf.SOCP")
col.names = "confidence,budget,return,method"
write(col.names, file = file.results, append = FALSE)

nStates = 5
prior <- rep(1, nStates)
num_confs = 5
confidences <- seq(0.5, 0.999, length.out = num_confs)

num_samples_from_truth <- 20
num_bayes_samples <- 20

num.runs <- 100

weights.uniform <- rep(1, nStates)
for (run in 1:num.runs) {
  z <- seq(1,nStates)
  #z <- runif(nStates, min = -10, max = 10)
  #z <- c(1 , rep(0, nStates-1))

  true_distribution <- rdirichlet(1, prior)
  samples <- rmultinom(1, size = num_samples_from_truth, prob = true_distribution)
  fci_nominal_trp <- samples / sum(samples)

  posteriori_samples <- rdirichlet(num_bayes_samples, samples + prior)
  bayes_nominal_trp <- colMeans(posteriori_samples)

  weights.l1.anlyt <- compute.weights(z = z, norm = "L1", solution = "analytical")

  for (confidence in confidences) {
    ####################################################
    ## Calculate the budget L1 - uniform
    ####################################################
    psi.l1.hff <-
      l1.weighted.size.hoeffding(
        nsamples = num_samples_from_truth,
        nstates = nStates,
        nactions = 1,
        confidence = confidence,
        weights = weights.uniform
      )



    ####################################################
    ## Calculate the budget L1 - weighted
    ####################################################

    psi.w.l1.hff <-
      l1.weighted.size.hoeffding(
        nsamples = num_samples_from_truth,
        nstates = nStates,
        nactions = 1,
        confidence = confidence,
        weights = weights.l1.anlyt
      )


    ####################################################
    ## Calculate the returns L1 - uniform
    ####################################################

    return.l1.hff <- rcraam::worstcase_l1(z,
                                            fci_nominal_trp,
                                            psi.l1.hff)$value


    ####################################################
    ## Calculate the returns L1 - weighted
    ####################################################

    return.w.l1.hff.anlyt <-rcraam::worstcase_l1_w(z,
                                                 fci_nominal_trp,
                                                 weights.l1.anlyt,
                                                 psi.w.l1.hff)$value

    # NOTE: psi.w.l1.socp depends on weights and weights depends on psi (budget)
    # So we choose uniform weights to find the psi (budget)
    #psi.l1.hff.socp <- psi.l1.hff
    #weights.l1.socp <- weights.uniform
    psi.l1.hff.socp <- psi.w.l1.hff
    weights.l1.socp <- weights.l1.anlyt

    for(i in 1:3){
      weights.l1.socp <- compute.weights(z = z,
                                         norm = "L1",
                                         solution = "socp",
                                         p_bar = fci_nominal_trp,
                                         psi = psi.l1.hff.socp )

      psi.l1.hff.socp <-  l1.weighted.size.hoeffding(
        nsamples = num_samples_from_truth,
        nstates = nStates,
        nactions = 1,
        confidence = confidence,
        weights = weights.l1.socp
      )
    }
    return.w.l1.hff.socp <-rcraam::worstcase_l1_w(z,
                                                fci_nominal_trp,
                                                weights.l1.socp,
                                              psi.l1.hff.socp)$value


     budgets <-
        c(
          psi.l1.hff,
          psi.w.l1.hff,
          psi.l1.hff.socp
        )
    returns <-
        c(
           return.l1.hff,
           return.w.l1.hff.anlyt,
           return.w.l1.hff.socp
        )

    d = cbind(confidence, budgets, returns, method_names)
    write.table(
        d,
        file = file.results,
        append = TRUE,
        sep = ",",
        row.names = FALSE,
        col.names = FALSE
    )
  }
}
```






# plot the result
```{r}
dir.name = "./results/"
file.name = "single_Bellman_update"
file.ext = ".csv"
file.results <- paste(dir.name, file.name, file.ext, sep = "")


df <- read.csv(file = file.results, header = TRUE, sep = ",")
df <- df %>% group_by(confidence, method) %>% summarise(return = mean(return), budget = mean(budget))


plot.res.color(df, file.name)
```



# L1 Baysian

```{r}
set.seed(1658)
dir.name = "../results/"
file.name = "single_Bellman_update"
file.ext = ".csv"
file.results <- paste(dir.name, file.name, file.ext, sep = "")

method_names = list("L1.Bay",
                    "w.L1.Bay.anlyt",
                    "w.L1.Bay.SOCP")
col.names = "confidence,budget,return,method"
write(col.names, file = file.results, append = FALSE)

nStates = 10
prior <- rep(1, nStates)
num_confs = 5
confidences <- seq(0.5, 0.999, length.out = num_confs)

num_samples_from_truth <- 20
num_bayes_samples <- 20

num.runs <- 100

weights.uniform <- rep(1, nStates)


for (run in 1:num.runs) {
  z <- runif(nStates, min = -10, max = 10)

  true_distribution <- rdirichlet(1, prior)
  samples <- rmultinom(1, size = num_samples_from_truth, prob = true_distribution)
  fci_nominal_trp <- samples / sum(samples)

  posteriori_samples <- rdirichlet(num_bayes_samples, samples + prior)
  bayes_nominal_trp <- colMeans(posteriori_samples)

  weights.l1.anlyt <- compute.weights(z = z, norm = "L1", solution = "analytical")

  for (confidence in confidences) {
    ####################################################
    ## Calculate the budget L1 - uniform
    ####################################################
    psi.l1.bay <-
      l1.size.bayes(
        bayes_nominal_trp,
        posteriori_samples,
        nactions = 1,
        confidence,
        weights = weights.uniform
      )
    ####################################################
    ## Calculate the budget L1 - weighted
    ####################################################

    psi.w.l1.bay <-
      l1.size.bayes(
        bayes_nominal_trp,
        posteriori_samples,
        nactions = 1,
        confidence,
        weights = weights.l1.anlyt
      )


    ####################################################
    ## Calculate the returns L1 - uniform
    ####################################################

    return.l1.bay <- rcraam::worstcase_l1_w(z,
                                            bayes_nominal_trp,
                                            weights.uniform,
                                            psi.l1.bay)$value


    ####################################################
    ## Calculate the returns L1 - weighted
    ####################################################

    return.w.l1.bay.anlyt <- rcraam::worstcase_l1_w(z,
                                                 bayes_nominal_trp,
                                                 weights.l1.anlyt,
                                                 psi.w.l1.bay)$value

    # NOTE: psi.w.l1.socp depends on weights and weights depends on psi (budget)
    # So we choose uniform weights to find the psi (budget)
    #psi.l1.bay.socp <- psi.l1.bay
    #weights.l1.socp <- weights.uniform
    psi.l1.bay.socp <- psi.w.l1.bay
    weights.l1.socp <- weights.l1.anlyt

    for(i in 1:3){
      weights.l1.socp <- compute.weights(z = z,
                                         norm = "L1",
                                         solution = "socp",
                                         p_bar = bayes_nominal_trp,
                                         psi = psi.l1.bay.socp )

      psi.l1.bay.socp <- l1.size.bayes(
        bayes_nominal_trp,
        posteriori_samples,
        nactions = 1,
        confidence,
        weights = weights.l1.socp
      )

    }
    return.w.l1.bay.socp <-rcraam::worstcase_l1_w(z,
                                                 bayes_nominal_trp,
                                                 weights.l1.socp,
                                            psi.l1.bay.socp)$value


     budgets <-
        c(
          psi.l1.bay,
          psi.w.l1.bay,
          psi.l1.bay.socp
        )
    returns <-
        c(
           return.l1.bay,
           return.w.l1.bay.anlyt,
           return.w.l1.bay.socp
        )

    d = cbind(confidence, budgets, returns, method_names)
    write.table(
        d,
        file = file.results,
        append = TRUE,
        sep = ",",
        row.names = FALSE,
        col.names = FALSE
    )


  }
}
```

# L_inf Hoeffding

```{r}
#set.seed(1658)
dir.name = "../results/"
file.name = "single_Bellman_update"
file.ext = ".csv"
file.results <- paste(dir.name, file.name, file.ext, sep = "")

method_names = list("Linf.Hf",
                    "w.Linf.Hf.anlyt",
                    "Linf.Bay",
                    "w.Linf.Bay")
col.names = "confidence,budget,return,method"
write(col.names, file = file.results, append = FALSE)

nStates = 10
prior <- rep(1, nStates)
num_confs = 5
confidences <- seq(0.5, 0.999, length.out = num_confs)

num_samples_from_truth <- 20
num_bayes_samples <- 20

num.runs <- 100
weights.uniform <- rep(1, nStates)

for (run in 1:num.runs) {
  z <- runif(nStates, min = -10, max = 10)

  true_distribution <- rdirichlet(1, prior)
  samples <- rmultinom(1, size = num_samples_from_truth, prob = true_distribution)
  fci_nominal_trp <- samples / sum(samples)

  posteriori_samples <- rdirichlet(num_bayes_samples, samples + prior)
  bayes_nominal_trp <- colMeans(posteriori_samples)

  weights.linf.anlyt <- compute.weights(z = z, norm = "Linf", solution = "analytical")

  for (confidence in confidences) {
    ####################################################
    ## Calculate the budget Linf - uniform
    ####################################################
    psi.linf.hff <-
      linf.weighted.size.hoeffding(
        nsamples = num_samples_from_truth,
        nstates = nStates,
        nactions = 1,
        confidence = confidence,
        weights = weights.uniform
    )

    psi.linf.bay <- linf.size.bayes(
      bayes_nominal_trp,
      posteriori_samples,
      nactions = 1,
      confidence,
      weights = weights.uniform
    )

    ####################################################
    ## Calculate the budget Linf - weighted
    ####################################################

    psi.w.linf.hff <-
      linf.weighted.size.hoeffding(
        nsamples = num_samples_from_truth,
        nstates = nStates,
        nactions = 1,
        confidence = confidence,
        weights = weights.linf.anlyt
      )

    psi.w.linf.bay <- linf.size.bayes(
      bayes_nominal_trp,
      posteriori_samples,
      nactions = 1,
      confidence,
      weights = weights.linf.anlyt
    )


    ####################################################
    ## Calculate the returns L1 - uniform
    ####################################################

    return.linf.hff <- rcraam::worstcase_linf_wg(z,
                                            fci_nominal_trp,
                                            weights.uniform,
                                            psi.linf.hff)$obj

    return.linf.bay <- rcraam::worstcase_linf_wg(z,
                                                 bayes_nominal_trp,
                                                 weights.uniform,
                                                 psi.linf.bay)$obj
    ####################################################
    ## Calculate the returns Linf - weighted
    ####################################################

    return.w.linf.hff.anlyt <-rcraam::worstcase_linf_wg(z,
                                                 fci_nominal_trp,
                                                 weights.linf.anlyt,
                                                 psi.w.linf.hff)$obj

    return.w.linf.bay <- rcraam::worstcase_linf_wg(z,
                                                 bayes_nominal_trp,
                                                 weights.linf.anlyt,
                                                 psi.w.linf.bay)$obj


     budgets <-
        c(
          psi.linf.hff,
          psi.w.linf.hff,
          psi.linf.bay,
          psi.w.linf.bay
        )
    returns <-
        c(
           return.linf.hff,
           return.w.linf.hff.anlyt,
           return.linf.bay,
           return.w.linf.bay
        )

    d = cbind(confidence, budgets, returns, method_names)
    write.table(
        d,
        file = file.results,
        append = TRUE,
        sep = ",",
        row.names = FALSE,
        col.names = FALSE
    )
  }
}
```


